package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

type spdxJSON struct {
	LicenseListVersion string        `json:"licenseListVersion"`
	Licenses           []spdxLicense `json:"licenses"`
}

type spdxLicense struct {
	LicenseID             string `json:"licenseId"`
	Name                  string `json:"name"`
	IsDeprecatedLicenseID bool   `json:"isDeprecatedLicenseId"`
}

func fail(f string, a ...any) { fmt.Fprintf(os.Stderr, "error: "+f+"\n", a...); os.Exit(1) }

func main() {
	var spdxPath, aliasPath, outPath string
	flag.StringVar(&spdxPath, "spdx", "", "path to SPDX licenses.json")
	flag.StringVar(&aliasPath, "aliases", "", "path to custom aliases yaml (optional)")
	flag.StringVar(&outPath, "out", "spdx_generated.go", "output file")
	flag.Parse()
	if spdxPath == "" {
		fail("-spdx required")
	}
	data, err := os.ReadFile(spdxPath)
	if err != nil {
		fail("read: %v", err)
	}
	var doc spdxJSON
	if err := json.Unmarshal(data, &doc); err != nil {
		fail("unmarshal: %v", err)
	}

	type meta struct {
		ID, Name   string
		Deprecated bool
	}
	canon := map[string]meta{}
	for _, l := range doc.Licenses {
		canon[strings.ToUpper(l.LicenseID)] = meta{ID: l.LicenseID, Name: l.Name, Deprecated: l.IsDeprecatedLicenseID}
	}
	alias := map[string]string{}
	add := func(k, id string) {
		k = normKey(k)
		if k == "" {
			return
		}
		if _, ok := alias[k]; !ok {
			alias[k] = id
		}
	}
	for _, m := range canon {
		id := m.ID
		add(id, id)
		add(strings.ToUpper(id), id)
		add(strings.ReplaceAll(id, "-", ""), id)
		add(strings.ReplaceAll(id, "-", " "), id)
	}
	// custom aliases (simple yaml: key: value)
	if aliasPath != "" {
		if b, err := os.ReadFile(aliasPath); err == nil {
			for _, line := range bytes.Split(b, []byte("\n")) {
				s := strings.TrimSpace(string(line))
				if s == "" || strings.HasPrefix(s, "#") {
					continue
				}
				parts := strings.SplitN(s, ":", 2)
				if len(parts) != 2 {
					continue
				}
				k := strings.TrimSpace(parts[0])
				v := strings.TrimSpace(parts[1])
				v = strings.Trim(v, "\"'")
				if _, ok := canon[strings.ToUpper(v)]; ok {
					alias[normKey(k)] = v
				}
			}
		}
	}
	// build slices
	type genCanon struct {
		UpperID, ID, Name string
		Deprecated        bool
	}
	var canonList []genCanon
	for up, m := range canon {
		canonList = append(canonList, genCanon{UpperID: up, ID: m.ID, Name: m.Name, Deprecated: m.Deprecated})
	}
	sort.Slice(canonList, func(i, j int) bool { return canonList[i].ID < canonList[j].ID })
	var aliasList []struct{ K, V string }
	for k, v := range alias {
		aliasList = append(aliasList, struct{ K, V string }{k, v})
	}
	sort.Slice(aliasList, func(i, j int) bool {
		if aliasList[i].K == aliasList[j].K {
			return aliasList[i].V < aliasList[j].V
		}
		return aliasList[i].K < aliasList[j].K
	})

	// Prepare padded rows for diff-friendly alignment.
	maxCanonKey := 0
	for _, c := range canonList {
		if l := len(c.UpperID); l > maxCanonKey {
			maxCanonKey = l
		}
	}
	type canonRow struct {
		Key, Pad, ID, Name string
		Deprecated         bool
	}
	canonRows := make([]canonRow, 0, len(canonList))
	for _, c := range canonList {
		pad := strings.Repeat(" ", maxCanonKey-len(c.UpperID))
		canonRows = append(canonRows, canonRow{Key: c.UpperID, Pad: pad, ID: c.ID, Name: c.Name, Deprecated: c.Deprecated})
	}
	maxAliasKey := 0
	for _, a := range aliasList {
		if l := len(a.K); l > maxAliasKey {
			maxAliasKey = l
		}
	}
	type aliasRow struct{ Key, Pad, V string }
	aliasRows := make([]aliasRow, 0, len(aliasList))
	for _, a := range aliasList {
		pad := strings.Repeat(" ", maxAliasKey-len(a.K))
		aliasRows = append(aliasRows, aliasRow{Key: a.K, Pad: pad, V: a.V})
	}
	tpl := template.Must(template.New("g").Funcs(template.FuncMap{"esc": func(s string) string { return s }}).Parse(tplSrc))
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, map[string]any{"Canon": canonRows, "Aliases": aliasRows, "Version": doc.LicenseListVersion}); err != nil {
		fail("tpl: %v", err)
	}
	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		fail("write: %v", err)
	}
	fmt.Printf("Generated %s (canon=%d aliases=%d)\n", filepath.Base(outPath), len(canonList), len(aliasList))
}

func normKey(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	var b strings.Builder
	lastSpace := false
	for _, r := range s {
		switch r {
		case '-', '_', '.', '/', '+':
			r = ' '
		}
		if r == ' ' || r == '\t' || r == '\n' || r == '\r' {
			if lastSpace {
				continue
			}
			lastSpace = true
			b.WriteByte(' ')
			continue
		}
		lastSpace = false
		b.WriteRune(r)
	}
	return strings.ToUpper(strings.TrimSpace(b.String()))
}

const tplSrc = `// Code generated by SPDX generator; DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// Generated from SPDX license list version {{ .Version }}.
package licenses

import "strings"

// SPDXLicenseListVersion indicates upstream list version.
const SPDXLicenseListVersion = "{{ .Version }}"

// spdxMeta holds minimal metadata for an SPDX license identifier.
type spdxMeta struct { ID, Name string; Deprecated bool }

// spdxCanonical maps the UPPER-CASE form of an SPDX identifier to its
// canonical casing plus metadata. One entry per line for diff clarity.
var spdxCanonical = map[string]spdxMeta{
{{ range .Canon }}	"{{ .Key }}":{{ .Pad }} { ID: "{{ .ID }}", Name: {{ printf "%q" .Name }}, Deprecated: {{ .Deprecated }} },
{{ end }}}

// spdxAlias maps a normalized alias token (uppercase words separated by single spaces)
// to the canonical SPDX identifier. Lines are padded for minimal diff churn.
var spdxAlias = map[string]string{
{{ range .Aliases }}	"{{ .Key }}":{{ .Pad }} "{{ .V }}",
{{ end }}}

// normKeyGenerated mirrors the normalization used during generation (duplicated for independence).
func normKeyGenerated(s string) string {
	s = strings.TrimSpace(s)
	if s == "" { return "" }
	var b strings.Builder
	lastSpace := false
	for _, r := range s {
		switch r {
		case '-', '_', '.', '/', '+':
			r = ' '
		}
		if r == ' ' || r == '\t' || r == '\n' || r == '\r' {
			if lastSpace { continue }
			lastSpace = true
			b.WriteByte(' ')
			continue
		}
		lastSpace = false
		b.WriteRune(r)
	}
	return strings.ToUpper(strings.TrimSpace(b.String()))
}

// GeneratedNormalize resolves an arbitrary raw license string to a canonical SPDX ID and metadata.
// It first attempts an exact (case-insensitive uppercase) match, then falls back to alias lookup.
func GeneratedNormalize(raw string) (id string, meta spdxMeta, ok bool) {
	r := strings.TrimSpace(raw)
	if r == "" { return "", spdxMeta{}, false }
	u := strings.ToUpper(r)
	if m, ok := spdxCanonical[u]; ok { return m.ID, m, true }
	k := normKeyGenerated(r)
	if id, ok := spdxAlias[k]; ok { return id, spdxCanonical[strings.ToUpper(id)], true }
	return "", spdxMeta{}, false
}
`
